# Generated by Django 5.1.7 on 2025-04-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aether_electricity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalutility',
            old_name='tariff_maxtrix',
            new_name='tariff_matrix',
        ),
    ]
